imports:
  - { resource: config.yml }

oneup_flysystem:
  adapters:
    uploads:
      local:
        directory: "%kernel.root_dir%/../web/uploads"

  filesystems:
    uploads:
      adapter: uploads
      alias: upload_filesystem