imports:
  - { resource: config.yml }

framework:
  router:
    resource: '%kernel.project_dir%/resources/config/routing_development.yml'
  profiler: ~

web_profiler:
  toolbar: true

oneup_flysystem:
  adapters:
    uploads:
      local:
        directory: "%kernel.root_dir%/../web/uploads"

  filesystems:
    uploads:
      adapter: uploads
      alias: upload_filesystem